name: Build Docs Artifacts
description: Builds the documentation
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/pnpm-setup

    - name: Build Docs
      shell: bash
      run: npm run build
