name: Build Docs Artifacts
description: Builds the documentation artifacts including Docusaus, Sample App and Designer
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for package registry authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/pnpm-setup

    - name: Build Docs
      shell: bash
      run: |
        rm -rf build
        npm run build