name: Build Docs Artifacts
description: Builds the documentation artifacts including Docusaus, Sample App and Designer
inputs:
  PERSONAL_ACCESS_TOKEN:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/pnpm-setup

    - name: Build Docs
      shell: bash
      run: |
        pnpm install --no-frozen-lockfile
        npm run build
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: "https://npm.pkg.github.com"
        scope: "@public-ui"
