name: Build Docs Artifacts
description: Builds the documentation artifacts including Docusaus, Sample App and Designer
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for package registry authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/pnpm-setup

    - name: Build Docs
      shell: bash
      run: |
        rm -rf build
        npm run build
        mv build next

    - uses: actions/setup-node@v6
      with:
        node-version: 22
        registry-url: https://npm.pkg.github.com
        scope: '@public-ui'

    - name: Download Docs (v3)
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        npm pack @public-ui/docs-v3@latest > /dev/null
        tar -xzvf public-ui-*.tgz > /dev/null

        mv package/build build
        mv next build/next

        rm -rf package *.tgz

    - name: Download Docs (v2)
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        npm pack @public-ui/docs-v2@latest > /dev/null
        tar -xzvf public-ui-*.tgz > /dev/null

        rm -rf build/v2
        mkdir -p build/v2
        mv package/build/* build/v2/

        rm -rf package *.tgz

    - name: Download designer (v1)
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        npm pack @public-ui/designer@^1
        tar -xzvf public-ui-*.tgz > /dev/null

        rm -rf build/v1/designer
        mkdir -p build/v1
        mv package/dist build/v1/designer

        rm -rf package *.tgz

    - name: Download designer (v2)
      env:
        NODE_AUTH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: |
        npm pack @public-ui/designer@^2
        tar -xzvf public-ui-*.tgz > /dev/null

        rm -rf build/v2/designer
        mkdir -p build/v2
        mv package/dist build/v2/designer

        rm -rf package *.tgz
