# References:
# - https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
# - https://github.com/pnpm/action-setup

name: pnpm Setup
description: Install Node and pnpm, install dependencies
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - run: pnpm install
      shell: bash
