# References:
# - https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
# - https://github.com/pnpm/action-setup

name: pnpm Setup
description: Install Node and pnpm, install dependencies
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: pnpm

    - run: pnpm install
      shell: bash
