export type ComponentSynonyms = {
	[key: string]: string[];
};

export const COMPONENT_SYNONYMS: ComponentSynonyms = {
	accordion: ['Collapse'],
	alert: ['Message', 'Alerts', 'Toaster', 'Snackbar'],
	avatar: ['Persona'],
	badge: ['Badges'],
	breadcrumb: ['Breadcrumbs'],
	button: ['Buttons', 'Button Icons'],
	'button-group': ['Button group', 'Button Groups'],
	'button-link': ['Button', 'Buttons', 'Button Icons'],
	card: ['Cards'],
	combobox: ['Autocomplete', 'Select', 'Dropdown'],
	details: ['Disclosure', 'Collapse', 'Summary Detail'],
	dialog: ['Modal', 'Modal dialog', 'Corner Dialog', 'Prompt'],
	image: ['Img', 'Thumbnail'],
	'input-date': [
		'DatePicker',
		'Datetime Picker',
		'Date picker',
		'Date',
		'Calendar',
		'Datepickers',
		'Datetime Picker.Popup',
		'Datepicker dialog',
	],
	'input-file': ['Upload', 'File input', 'File uploader', 'File', 'Filepicker', 'File Selector'],
	'input-radio': ['ChoiceGroup', 'Radio', 'Radios', 'Radio Button', 'Radio Buttons'],
	'input-range': ['Slider', 'Sliders', 'Range'],
	'input-text': [
		'Input',
		'Textfield',
		'FormControl',
		'Text input',
		'Text',
		'Text Input',
		'TextField',
		'Text field',
		'InputText',
		'input',
		'Text Field',
		'TextInput',
	],
	modal: ['Modal', 'Modal dialog', 'Corner Dialog', 'Prompt'],
	nav: ['Menu', 'Dropdowns (menu)'],
	select: ['Autocomplete', 'Datalist', 'Select Menu', 'Combobox', 'Dropdown', 'Picker', 'Selection Dropdown'],
	spin: ['Placeholder', 'Placeholders', 'Skeleton', 'Shimmer'],
	table: ['Tables', 'Dynamic table', 'Data table', 'Data Tables', 'DetailsList', 'Tree Grid'],
	tabs: ['Navs & tabs'],
	toaster: ['Toast', 'Toasts', 'Notification'],
	tooltip: ['Tooltips', 'Inline dialog', 'Popover'],
	tree: ['List', 'List group', 'Ul', 'Ol'],
};
